name: .NET CI/CD with Docker and Render

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  ASPNETCORE_ENVIRONMENT: Production
  ExternalApiUrl: ${{ secrets.EXTERNAL_API_URL }}
  MySecretKey: ${{ secrets.MY_SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore DDDPlayGround.sln

    - name: Build
      run: dotnet build DDDPlayGround.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
  run: dotnet publish DDDPlayGround.Host/DDDPlayGround.Host.csproj --configuration Release --output ./publish --no-build

    - name: Build Docker image
      run: docker build -t yourdockerhubusername/dddplayground:latest .

    # Optional: Push docker image (uncomment and add secrets if you want)
    #- name: Login to DockerHub
    #  uses: docker/login-action@v2
    #  with:
    #    username: ${{ secrets.DOCKER_USERNAME }}
    #    password: ${{ secrets.DOCKER_PASSWORD }}

    #- name: Push Docker image
    #  run: docker push yourdockerhubusername/dddplayground:latest

    - name: Deploy to Render
      run: |
        echo "Add your Render deployment commands here"
